services:
  vdns_server:
    image: ghcr.io/vlayer-xyz/vdns_server:0.2.0-nightly-20250423-82a6f8a555f221fb615762fedd26bc534fd0df83
    container_name: vlayer-vdns-server
    platform: linux/amd64
    environment:
      RUST_LOG: "info,vdns_server=debug"
    command: ["-l", "0.0.0.0:3002"]
    ports:
      - "127.0.0.1:3002:3002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 5s
      timeout: 60s
      retries: 10
      start_period: 5s