[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[dependencies]
"@openzeppelin-contracts" = "5.0.1"
forge-std = "1.9.4"
risc0-ethereum = { version = "2.0.0", url = "https://github.com/vlayer-xyz/risc0-ethereum/releases/download/v2.0.0-soldeer/contracts.zip" }
vlayer = "0.1.0-nightly-20250403-d442cea"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
